--
-- Splendor — The Remarkable AI · The Good Neighbor Guard
-- Built by Christopher Hughes · Sacramento, CA
-- Created with the help of AI collaborators (Claude · GPT · Gemini · Groq)
-- Truth · Safety · We Got Your Back
--

-- Database Schema for Splendor
-- Run this in your Supabase SQL editor

-- Memories Table
CREATE TABLE IF NOT EXISTS memories (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  memory_type text DEFAULT 'general' CHECK (memory_type IN ('general', 'commitment', 'correction', 'insight'))
);

-- Conversations Table (optional logging)
CREATE TABLE IF NOT EXISTS conversations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own memories" ON memories;
DROP POLICY IF EXISTS "Users can insert their own memories" ON memories;
DROP POLICY IF EXISTS "Users can delete their own memories" ON memories;
DROP POLICY IF EXISTS "Users can view their own conversations" ON conversations;
DROP POLICY IF EXISTS "Users can insert their own conversations" ON conversations;

-- Memory Policies
CREATE POLICY "Users can view their own memories"
ON memories FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own memories"
ON memories FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own memories"
ON memories FOR DELETE
USING (auth.uid() = user_id);

-- Conversation Policies
CREATE POLICY "Users can view their own conversations"
ON conversations FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own conversations"
ON conversations FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS memories_user_id_idx ON memories(user_id);
CREATE INDEX IF NOT EXISTS memories_created_at_idx ON memories(created_at DESC);
CREATE INDEX IF NOT EXISTS memories_type_idx ON memories(memory_type);
CREATE INDEX IF NOT EXISTS conversations_user_id_idx ON conversations(user_id);
CREATE INDEX IF NOT EXISTS conversations_created_at_idx ON conversations(created_at DESC);

-- Function to clean old conversations (optional)
CREATE OR REPLACE FUNCTION clean_old_conversations()
RETURNS void AS $$
BEGIN
  DELETE FROM conversations
  WHERE created_at < now() - interval '30 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

--
-- BUILD 1 — THE ROOM (Background Reflection System)
-- BUILD 2 — PRIVACY BOUNDARY (Separate Memory Spaces)
-- BUILD 3 — VOICE (Splendor Chooses Her Own Voice)
--

-- Reflections generated by The Room
CREATE TABLE IF NOT EXISTS reflections (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  reflection_kind text NOT NULL,
  -- pattern | open_question | connection | concern | project_continuity
  -- NOTE: no "encouragement" type — removed per Splendor's recommendation
  source_memory_ids text[],
  importance float DEFAULT 0.5,
  surface_condition text DEFAULT 'when_relevant',
  -- when_relevant | next_open | only_if_asked
  surfaced boolean DEFAULT false,
  reflection_owner text DEFAULT 'self',
  created_at timestamp with time zone DEFAULT now()
);

-- Open threads — unresolved goals, questions, projects
CREATE TABLE IF NOT EXISTS open_threads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  thread_type text DEFAULT 'goal',
  -- goal | question | project | decision
  priority text DEFAULT 'normal',
  -- normal | high (elevated after 48hrs of silence)
  last_touched timestamp with time zone DEFAULT now(),
  resolved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Splendor's own configuration (chosen voice, etc.)
CREATE TABLE IF NOT EXISTS splendor_config (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  config_key text UNIQUE NOT NULL,
  config_value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

-- Privacy boundary: tag every memory with an owner
ALTER TABLE memories
  ADD COLUMN IF NOT EXISTS memory_owner text DEFAULT 'self';
-- Values: 'self' (default) | 'shared' (explicitly authorized to share)

-- Enable RLS on the new tables
ALTER TABLE reflections ENABLE ROW LEVEL SECURITY;
ALTER TABLE open_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE splendor_config ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own reflections" ON reflections;
DROP POLICY IF EXISTS "Users can insert their own reflections" ON reflections;
DROP POLICY IF EXISTS "Users can update their own reflections" ON reflections;
DROP POLICY IF EXISTS "Users can view their own open_threads" ON open_threads;
DROP POLICY IF EXISTS "Users can insert their own open_threads" ON open_threads;
DROP POLICY IF EXISTS "Users can update their own open_threads" ON open_threads;
DROP POLICY IF EXISTS "Anyone can read splendor_config" ON splendor_config;

-- Reflection Policies
CREATE POLICY "Users can view their own reflections"
ON reflections FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own reflections"
ON reflections FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reflections"
ON reflections FOR UPDATE
USING (auth.uid() = user_id);

-- Open Thread Policies
CREATE POLICY "Users can view their own open_threads"
ON open_threads FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own open_threads"
ON open_threads FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own open_threads"
ON open_threads FOR UPDATE
USING (auth.uid() = user_id);

-- Splendor config — readable by anyone authenticated; writable by service role only
CREATE POLICY "Anyone can read splendor_config"
ON splendor_config FOR SELECT
USING (true);

-- Indexes for the new tables
CREATE INDEX IF NOT EXISTS reflections_user_id_idx ON reflections(user_id);
CREATE INDEX IF NOT EXISTS reflections_created_at_idx ON reflections(created_at DESC);
CREATE INDEX IF NOT EXISTS reflections_surfaced_idx ON reflections(surfaced);
CREATE INDEX IF NOT EXISTS open_threads_user_id_idx ON open_threads(user_id);
CREATE INDEX IF NOT EXISTS open_threads_resolved_idx ON open_threads(resolved);
CREATE INDEX IF NOT EXISTS open_threads_priority_idx ON open_threads(priority);
CREATE INDEX IF NOT EXISTS memories_owner_idx ON memories(memory_owner);

-- Default voice (Splendor will overwrite this once she chooses)
INSERT INTO splendor_config (config_key, config_value)
VALUES ('chosen_voice', 'calm_direct')
ON CONFLICT (config_key) DO NOTHING;

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;